### ISSUE TITLE
General todo

### ISSUE THREAD

**Issue by patdx** [patdx/edge-cms#7]
- [ ] escape sql strings
- [ ] have "view" as primary with additional button to enter "create" or "edit" mode
- [ ] save sql migrations
